### ISSUE TITLE
yanglint libyang err : Invalid default - value does not fit the type 

### ISSUE THREAD

**Issue by dperdices** [YangCatalog/yang-validator-extractor#85]
Hi again,

Aside from the previous issue, we are trying to investigate a validation error, and we are not fully understanding what is happening.

When validating [draft-ietf-ccamp-flexigrid-tunnel-yang](https://datatracker.ietf.org/doc/draft-ietf-ccamp-flexigrid-tunnel-yang/), we have the following yanglint error:
```
libyang err : Invalid default - value does not fit the type (Invalid identityref "flexi-ch-spc-6p25ghz" value - identity not found in module "ietf-flexi-grid-tunnel".). (Schema location /ietf-te:te/tunnels/tunnel/secondary-reverse-paths/secondary-reverse-path/path-out-segment/label-restrictions/label-restriction/label-step/technology/ietf-flexi-grid-tunnel:flexi-grid/flexi-grid-channel-spacing.)
```
But in the IETF tracker, also validated with yanglint ([see the validation output](https://datatracker.ietf.org/doc/draft-ietf-ccamp-flexigrid-tunnel-yang/)), there is no error, and we are not really sure why validation outputs are different (and which we should trust :D).

Thank you in advance for your help!

**Comment by SlavomirMazurPantheon** [comment]
Hello,

This is probably due to different versions of the yanglint validator. 
Datatracker uses version yanglint SO 1.6.7 while YANG Catalog uses version yanglint SO 2.0.112.

Regards,
Slavomir Mazur

**Comment by dperdices** [comment]
Thank you! We will look then at the validation output carefully, bearing in mind that IETF datatracker older version might not be reporting all errors/warning.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

you are welcome and I also thank you for pointing out the issues.

Regards,
Slavomir Mazur
